version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URI: ${DATABASE_URI}
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    environment:
      NODE_ENV: production
      DATABASE_URI: ${DATABASE_URI}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      PAYLOAD_CONFIG_PATH: dist/payload.config.js
    ports:
      - "3000:3000"
